# Generated by Django 3.2.1 on 2023-06-19 08:50

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='cloud7', max_length=255, verbose_name='标题')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
            ],
        ),
    ]
