# Generated by Django 3.2.1 on 2023-06-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpdocuments',
            options={'verbose_name': '帮助文档', 'verbose_name_plural': '帮助文档'},
        ),
    ]
