apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: {{ .Values.namespace }} 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.redis.storage }}  
  storageClassName:  {{ .Values.storageClassName }} 
  volumeMode: Filesystem