apiVersion: v1
kind: Service
metadata:
  name: cmdb-svc
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: cmdb
  ports:
    - name: cmdb
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
