# Generated by Django 3.2.1 on 2023-06-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='集群名字')),
                ('kubeconfig', models.TextField(default='', verbose_name='kubeconfig内容')),
            ],
            options={
                'verbose_name': '集群配置',
                'verbose_name_plural': '集群配置',
            },
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='配置名')),
                ('config', models.TextField(default='', verbose_name='配置内容')),
            ],
            options={
                'verbose_name': '自定义变量',
                'verbose_name_plural': '自定义变量',
            },
        ),
        migrations.CreateModel(
            name='ecsPm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cloud7', max_length=255, verbose_name='项目名')),
                ('Repositories', models.CharField(choices=[('git', 'New'), ('svn', 'svn')], default=0, max_length=255, verbose_name='代码仓库')),
                ('git', models.CharField(default='https://github.com/innet8/cloud7.git', max_length=255, verbose_name='git地址')),
                ('branch', models.CharField(default='master', max_length=255, verbose_name='分支')),
                ('cmd', models.CharField(default='bash -x cmd install', max_length=255, verbose_name='打包命令')),
                ('package', models.CharField(default='', max_length=255, verbose_name='打包工具版本')),
            ],
            options={
                'verbose_name': 'ecs项目管理',
                'verbose_name_plural': 'ecs项目管理',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, unique=True, verbose_name='主机名')),
                ('internal_ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='内网 IP 地址')),
                ('external_ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='外网 IP 地址')),
                ('ssh_username', models.CharField(max_length=255, verbose_name='SSH 用户名')),
                ('ssh_password', models.CharField(max_length=255, verbose_name='SSH 密码')),
                ('os_version', models.CharField(blank=True, max_length=255, null=True, verbose_name='操作系统版本')),
            ],
            options={
                'verbose_name': '主机配置',
                'verbose_name_plural': '主机配置',
            },
        ),
        migrations.CreateModel(
            name='k8sPm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='cloud7', max_length=255, verbose_name='项目名')),
                ('Repositories', models.CharField(choices=[('git', 'New'), ('svn', 'svn')], default=0, max_length=255, verbose_name='代码仓库类型')),
                ('git', models.CharField(default='https://github.com/innet8/cloud7.git', max_length=255, verbose_name='git地址')),
                ('branch', models.CharField(default='master', max_length=255, verbose_name='分支')),
                ('cmd', models.CharField(default='bash -x cmd install', max_length=255, verbose_name='打包命令')),
                ('dockerfile', models.TextField(default='k8s', max_length=255, verbose_name='dockerfile')),
                ('env', models.TextField(default='\n#####env config\nAPP_NAME=HiCloud\nAPP_ENV=local\nAPP_KEY=base64:3b8bGAYz6khm9MTVA9MoRxXPElPs9P99bb37Z+A35Xc=\nAPP_DEBUG=false\nAPP_SCHEME=auto\nAPP_URL=https://hicloud.keli.vip\nAPP_DEV_URL=http://localhost:9998\n\n', max_length=255, verbose_name='env')),
                ('domain', models.TextField(default='cloud7.keli.vip', max_length=255, verbose_name='部署域名')),
            ],
            options={
                'verbose_name': 'k8s项目管理',
                'verbose_name_plural': 'k8s项目管理',
            },
        ),
    ]
