# Generated by Django 3.2.1 on 2023-06-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8spm',
            name='domain',
            field=models.CharField(default='cloud7.keli.vip', max_length=255, verbose_name='部署域名'),
        ),
    ]
