# Generated by Django 3.2.1 on 2023-06-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0002_alter_k8spm_domain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='k8spm',
            options={'verbose_name': 'k8s项目', 'verbose_name_plural': 'k8s项目'},
        ),
        migrations.AlterField(
            model_name='k8spm',
            name='Repositories',
            field=models.CharField(choices=[('git', 'git'), ('svn', 'svn')], default=0, max_length=255, verbose_name='代码仓库类型'),
        ),
    ]
