# Generated by Django 3.2.1 on 2023-06-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0003_auto_20230619_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8spm',
            name='init',
            field=models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='初始化命令'),
        ),
        migrations.AlterField(
            model_name='k8spm',
            name='dockerfile',
            field=models.TextField(default='"\nFROM  kuaifan/php:swoole-8.0.rc9\nCOPY ./co /var/www\n', max_length=255, verbose_name='dockerfile'),
        ),
    ]
