# Generated by Django 3.2.1 on 2023-06-19 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0004_auto_20230619_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8spm',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='k8spm',
            name='deoloy_status',
            field=models.CharField(choices=[('未发布', '未发布'), ('发布中', '发布中'), ('已发布', '已发布')], default=0, max_length=255, verbose_name='发布状态'),
        ),
        migrations.AddField(
            model_name='k8spm',
            name='helm',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='helm'),
        ),
        migrations.AddField(
            model_name='k8spm',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='发布状态'),
        ),
        migrations.AddField(
            model_name='k8spm',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='k8spm',
            name='version',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='当前版本'),
        ),
    ]
