# Generated by Django 3.2.1 on 2023-06-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0005_auto_20230619_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='k8spm',
            name='status',
        ),
    ]
