# Generated by Django 3.2.1 on 2023-06-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doc', '0001_initial'),
        ('ConfCen', '0006_remove_k8spm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8spm',
            name='help',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pk_help', to='Doc.helpdocuments', verbose_name='帮助文档'),
        ),
        migrations.AlterField(
            model_name='k8spm',
            name='dockerfile',
            field=models.TextField(default='\nFROM  kuaifan/php:swoole-8.0.rc9\nCOPY ./co /var/www\n', max_length=255, verbose_name='dockerfile'),
        ),
    ]
