# Generated by Django 3.2.1 on 2023-06-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfCen', '0007_auto_20230619_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8spm',
            name='init',
            field=models.TextField(blank=True, default="echo 'hello world'", max_length=255, null=True, verbose_name='初始化命令'),
        ),
    ]
